language: python
script: utils/deploy.sh
before_install: sudo add-apt-repository -y ppa:openstack-ubuntu-testing/havana &&
  sudo apt-get update && sudo apt-get install autopoint qemu qemu-system build-essential
  liblzma-dev && git clone https://github.com/jnovy/pxz && cd pxz && make && sudo
  make install && cd ..
deploy:
  provider: releases
  api_key:
    secure: M04JvkdmAyFLRhq7iU+hW7QFJKipwiy/2FSKo2nW5yXLw8nOl+F3Cj2u8UhePrs2OdFTnYrcLJAgS3CUbb/GjtitZzT55T1y8i7YsmPXJEzDKE15qtI1EzvIEXpQKpYMO9uiZszuOyXEye7XvfqFzLAEwh1KE/LStJezRnqkD7M=
  file: system.img.xz
  skip_cleanup: true
  on:
    repo: konfiot/PRoq
