language: python
script: utils/deploy.sh
before_install : "sudo add-apt-repository -y ppa:openstack-ubuntu-testing/havana && sudo apt-get update && sudo apt-get install autopoint qemu qemu-system libc6-dev-armhf-cross bsdtar libpopt0 libpopt-dev fakeroot build-essential gcc-arm-linux-gnueabihf patch libarchive-dev && wget https://my.bitcasa.com/download-send/8275189836e36e7bf8b9abc04e734c1135eb2da75c1fa4ae4a10189512d9db43/2185853b873a60c0a9fe8c3c617d9b0b6a9c592fd4355182292eecc0df692fa7/pxz.deb?size=10410 && dpkg --install pxz.deb"
notifications:
  email: false
env:
  global: 
    - secure: "TVxwOjO9/VWQECt8ylwqT4UnLjIxuDWgfgMO1u95WUf3kjJy/3VKb2JA8iG7SXpXss4ooc6EX5peOo46/54QWFrngdeD49+tFkBsvMXbue5bVHLuCIjNcnTzt1Lp8WtnB3zvwmVNdzAGnpMxxvEej15ZAo1cBAqCh0zyviyP6Ho="

